/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.timeline.jsonc --env-file=/dev/null --include-runtime=false` (hash: ef7fd07fffe351a56a8c4cc4d44f236d)
interface __BaseEnv_Env {
	TIMELINE_DB: D1Database;
	ASSETS: Fetcher;
	ACCOUNT_SERVICE: Fetcher /* curiretas-account */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
