/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.timeline.jsonc --env-file=/dev/null --include-runtime=false --strict-vars=false` (hash: a5c64662cca9371a35c2c84218c1d484)
interface __BaseEnv_Env {
	TIMELINE_DB: D1Database;
	ASSETS: Fetcher;
	DISCORD_CONTRIBUTOR_ROLE_IDS: string;
	DISCORD_REVIEWER_ROLE_IDS: string;
	ACCOUNT_SERVICE: Fetcher /* curiretas-account */;
	DISCORD_MEMBERSHIP_SERVICE: Service /* entrypoint DiscordGuildMembershipService from curiretas-account */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DISCORD_CONTRIBUTOR_ROLE_IDS" | "DISCORD_REVIEWER_ROLE_IDS">> {}
}
