export const DAYS_IN_MONTH = 31;

export const EVENT_BAR_HEIGHT = 12;
export const EVENT_SUB_LANE_SPACING = 22;
export const LANE_PADDING = 10;
export const MIN_LANE_HEIGHT = 60;
export const TOP_OFFSET = 80;
export const LEFT_LABEL_WIDTH = 170;
export const RIGHT_PADDING = 20;
export const WIDTH = 1100;
export const FULL_HD_VIEWPORT_HEIGHT = 1080;
export const APP_HEADER_HEIGHT = 56;
export const TIMELINE_SVG_BOTTOM_PADDING = 40;
export const TIMELINE_ZOOM_CONTROL_RESERVED_HEIGHT = 64;
export const MIN_SINGLE_EVENT_LANE_HEIGHT =
  EVENT_BAR_HEIGHT + LANE_PADDING * 2;
export const MIN_VERTICAL_SCALE = 0.25;
export const LOW_DENSITY_SUMMARY_SCALE = 0.6;
export const MAX_FULL_HD_SINGLE_LANE_HEIGHT =
  FULL_HD_VIEWPORT_HEIGHT -
  APP_HEADER_HEIGHT -
  TOP_OFFSET -
  TIMELINE_SVG_BOTTOM_PADDING -
  TIMELINE_ZOOM_CONTROL_RESERVED_HEIGHT;
export const MAX_VERTICAL_SCALE =
  MAX_FULL_HD_SINGLE_LANE_HEIGHT / MIN_LANE_HEIGHT;
