import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const GENERATED_DATA_FILES = [
  {
    category: "hatsuboshiCommus",
    raw: "data/raw/worldline_commu/hatsuboshi_commu/001storyOfReiris.js",
    generated:
      "src/data/generated/worldline_commu/hatsuboshi_commu/001storyOfReiris.js",
  },
];

const HEADER = `// Generated by scripts/generate-data.mjs. Do not edit by hand.\n// Source of truth: data/raw/.\n\n`;

const KEY_ORDERS = {
  lane: ["id", "name", "color", "colorSource", "colorRoles", "events"],
  event: [
    "id",
    "start",
    "end",
    "title",
    "detail",
    "occurrenceType",
    "dateConfidence",
    "sourceBasis",
    "sourceStatus",
    "rangeReason",
    "worldlineId",
    "participants",
    "source",
    "sourceDetails",
    "conflicts",
    "note",
  ],
  date: ["year", "month", "day"],
  sourceDetail: ["id", "label", "url", "status", "claim", "supports"],
  conflict: ["summary", "sources", "resolution"],
};

function indent(level) {
  return "  ".repeat(level);
}

function isPlainObject(value) {
  return (
    value !== null &&
    typeof value === "object" &&
    !Array.isArray(value) &&
    Object.getPrototypeOf(value) === Object.prototype
  );
}

function classifyObject(value) {
  if ("events" in value) {
    return "lane";
  }

  if ("year" in value || "month" in value || "day" in value) {
    return "date";
  }

  if ("supports" in value || "claim" in value || "label" in value) {
    return "sourceDetail";
  }

  if ("summary" in value || "resolution" in value) {
    return "conflict";
  }

  if ("start" in value || "end" in value || "occurrenceType" in value) {
    return "event";
  }

  return "unknown";
}

function orderedKeys(value) {
  const keys = Object.keys(value);
  const order = KEY_ORDERS[classifyObject(value)] ?? [];
  const ordered = order.filter((key) => keys.includes(key));
  const remaining = keys.filter((key) => !order.includes(key)).sort();

  return [...ordered, ...remaining];
}

function renderObjectKey(key) {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
}

function renderInlineObject(value) {
  const parts = orderedKeys(value).map(
    (key) => `${renderObjectKey(key)}: ${renderValue(value[key], 0)}`,
  );

  return `{ ${parts.join(", ")} }`;
}

function renderArray(value, level) {
  if (value.length === 0) {
    return "[]";
  }

  const nextLevel = level + 1;
  const items = value.map(
    (item) => `${indent(nextLevel)}${renderValue(item, nextLevel)},`,
  );

  return `[\n${items.join("\n")}\n${indent(level)}]`;
}

function renderObject(value, level) {
  if (classifyObject(value) === "date") {
    return renderInlineObject(value);
  }

  const keys = orderedKeys(value);
  if (keys.length === 0) {
    return "{}";
  }

  const nextLevel = level + 1;
  const lines = keys.map((key) => {
    const propertyValue = value[key];
    if (propertyValue === undefined) {
      throw new Error(`Cannot generate undefined value at key "${key}".`);
    }

    return `${indent(nextLevel)}${renderObjectKey(key)}: ${renderValue(
      propertyValue,
      nextLevel,
    )},`;
  });

  return `{\n${lines.join("\n")}\n${indent(level)}}`;
}

function renderValue(value, level) {
  if (typeof value === "string") {
    return JSON.stringify(value);
  }

  if (typeof value === "number" || typeof value === "boolean" || value === null) {
    return JSON.stringify(value);
  }

  if (Array.isArray(value)) {
    return renderArray(value, level);
  }

  if (isPlainObject(value)) {
    return renderObject(value, level);
  }

  throw new Error(`Unsupported generated data value: ${String(value)}`);
}

function requireString(value, field, sourceFile) {
  if (typeof value !== "string" || value.trim() === "") {
    throw new Error(`${sourceFile}: ${field} must be a non-empty string.`);
  }
}

function requireDate(value, field, sourceFile, eventId) {
  if (!isPlainObject(value)) {
    throw new Error(`${sourceFile}: ${eventId}.${field} must be an object.`);
  }

  if (!Number.isInteger(value.year) || !Number.isInteger(value.month)) {
    throw new Error(
      `${sourceFile}: ${eventId}.${field} must include integer year and month.`,
    );
  }
}

function validateRawLane(lane, sourceFile) {
  if (!isPlainObject(lane)) {
    throw new Error(`${sourceFile}: default export must be a lane object.`);
  }

  requireString(lane.id, "id", sourceFile);
  requireString(lane.name, "name", sourceFile);
  requireString(lane.color, "color", sourceFile);

  if (!Array.isArray(lane.events)) {
    throw new Error(`${sourceFile}: events must be an array.`);
  }

  lane.events.forEach((event, index) => {
    const eventLabel = event?.id ?? `events[${index}]`;
    if (!isPlainObject(event)) {
      throw new Error(`${sourceFile}: ${eventLabel} must be an object.`);
    }

    requireString(event.id, `${eventLabel}.id`, sourceFile);
    requireString(event.title, `${eventLabel}.title`, sourceFile);
    requireString(event.detail, `${eventLabel}.detail`, sourceFile);
    requireString(event.occurrenceType, `${eventLabel}.occurrenceType`, sourceFile);
    requireDate(event.start, "start", sourceFile, eventLabel);
    requireDate(event.end, "end", sourceFile, eventLabel);
  });
}

async function importRawLane(sourceFile) {
  const rawUrl = pathToFileURL(path.resolve(sourceFile));
  const module = await import(`${rawUrl.href}?v=${Date.now()}`);
  validateRawLane(module.default, sourceFile);

  return module.default;
}

export async function renderGeneratedFile(file) {
  const lane = await importRawLane(file.raw);

  return `${HEADER}const lane = ${renderValue(lane, 0)};\n\nexport default lane;\n`;
}

export async function generateDataFiles({ check = false } = {}) {
  const results = [];

  for (const file of GENERATED_DATA_FILES) {
    const content = await renderGeneratedFile(file);
    let existing = null;

    try {
      existing = await fs.readFile(file.generated, "utf8");
    } catch (error) {
      if (error.code !== "ENOENT") {
        throw error;
      }
    }

    if (check) {
      results.push({
        ...file,
        fresh: existing === content,
        exists: existing !== null,
      });
      continue;
    }

    await fs.mkdir(path.dirname(file.generated), { recursive: true });
    await fs.writeFile(file.generated, content);
    results.push({ ...file, fresh: true, exists: true });
  }

  return results;
}

function formatCheckFailure(results) {
  const stale = results.filter((result) => !result.fresh);
  const lines = [
    "Generated data is stale. Run `npm run generate:data` and commit the result.",
  ];

  stale.forEach((result) => {
    const reason = result.exists ? "content differs" : "file is missing";
    lines.push(`- ${result.generated} (${reason}; source: ${result.raw})`);
  });

  return lines.join("\n");
}

async function main() {
  const check = process.argv.includes("--check");
  const results = await generateDataFiles({ check });

  if (check) {
    const stale = results.filter((result) => !result.fresh);
    if (stale.length > 0) {
      console.error(formatCheckFailure(results));
      process.exitCode = 1;
      return;
    }

    console.log(`Generated data freshness check passed for ${results.length} file(s).`);
    return;
  }

  console.log(`Generated ${results.length} data file(s).`);
}

const entrypoint = process.argv[1] ? fileURLToPath(import.meta.url) : "";

if (entrypoint && path.resolve(process.argv[1]) === entrypoint) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
